/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/components/layout/components/AppMain.vue')['default']
    Breadcrumb: typeof import('./src/components/layout/components/Breadcrumb/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Hamburger: typeof import('./src/components/layout/components/Hamburger/index.vue')['default']
    InnerLink: typeof import('./src/components/layout/components/InnerLink/index.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Link: typeof import('./src/components/layout/components/Sidebar/Link.vue')['default']
    Loading: typeof import('./src/components/loading/loading.vue')['default']
    Logo: typeof import('./src/components/layout/components/Sidebar/Logo.vue')['default']
    Navbar: typeof import('./src/components/layout/components/Navbar.vue')['default']
    NavTitle: typeof import('./src/components/layout/components/navTitle.vue')['default']
    ProgressBar: typeof import('./src/components/progressBar/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPane: typeof import('./src/components/layout/components/TagsView/ScrollPane.vue')['default']
    ShowImage: typeof import('./src/components/showImage/showImage.vue')['default']
    Sidebar: typeof import('./src/components/layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./src/components/layout/components/Sidebar/SidebarItem.vue')['default']
    TagsView: typeof import('./src/components/layout/components/TagsView/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPagination: typeof import('vant/es')['Pagination']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSkeleton: typeof import('vant/es')['Skeleton']
  }
}
